MODEL:
    DEVICE: 'cuda'
    SAM:
        CFG_PATH: './config/sam.yaml'
    CLIP:
        CFG_PATH: './config/clip.yaml'
INS_SEG:
    MAX_INPUT_SIZE: [1280, 1280]
    TOP_K_MASK_COUNT: 100
    CLS_SCORE_THRESH: 0.95
LOG:
    SAVE_DIR: './log'
    LEVEL: INFO
